dist: xenial
sudo: required
language: java
env:
  global:
  - SONATYPE_USERNAME=ph@phloc.com
  - secure: AVTpN0z7RyG3CTn46nNBLHptkB11i75creWd8hPLgAXDZZHEwyloR0z2UoJaOBiegksKwdgchq11aCyGebLVA0R8T6EwRQt41eoAKHfcjMVtlfCgl/Jkpdp7+OJn+cj
      fbBcWiUlXdeIf66ynkcBAx96Elxv3D+hV8sqxN2e6VeLTw9F6mj3PMk5gZlA+K57SKCxfw1RSreMF11RPCZtV+ol0vAUhNEbMaYFJ3w1322RX/yr0xbhgIJkJsUzQ2V5KZNRZuJYl4
      ly6mVcZK8y88eX4JMFTHiIglZ+jq9Lyt7xmmkR7ghprPSFgblm9Z/A8wTXmUva8m3SRFpEaYVfdreJqKOyDBSERI5l/7ZoJD5Q/5k1LZnC1uF1wkAdIt54hBMjdTACW8pw34Lv9wEa
      uUO3pTt1SKybxQI1+rvxYRCvLClb1u6FMBDEkQHcn+aNGl0nKUTArmg4p60MKvW1GCge+IYvLj/Fpgvmc3rFkgMwQPeyAYeQdpghh7VNVUNTFyv+ov8HydRZzFRcLkCZtg1eTNaJtR
      QHgHvtBbGQdRmmZHtAPK0o9Z25s76rXOkRd+B1iZEurOsvQIT8hsGRjhZL682cNHm4Jwe7R3qf2a0wyW/wGpXxUNFPOf1IW1xnAxE+RVO98g4IpbYkZD5e9bYdXhQmq6SDPH/a7jjo
      X5Nw=
  - secure: ta0qybYj281LsIj6L+byZBfMQkBorokFnY4Mb3lNGJx8/alCVqzRvDK4/6S4txH7Jv1PYP+87vELePpbp2fX/R7zhtYvkf6sHAscATAxdDa4pvu21+yENiaSwve99xGBVohjaeU1BSD4lN8yV9rsPCR9RdAvOT/xSAJECvvDCzmgpLZtS0wcCl8l90FtzUUY9jDwBkUjh9xvw+pzrfvJRThvnHmwt+QNUnPdP8Y7UQgmFaa85a2R9EFItVRiQX+tkfp695I/DysDB1QohtqkhZwS10r0bKIx9tvBeZQSogjBQ+nORGFMGKprnPKdQ4ohMDgzgj/QUOCb3FdWpH3NvWg60dSsT3Lgac68lUR6gYpMXClZqlpzoMPxPNg/vOH+hLtijPtG5RAk6B4k+sTmAH9RohbGZg1c9pQPPDTjgyobrfnkY+zhTOCGj+87ztMA3e9ZTq+WhMzGITRm5RzFbREMJK6LtLETk0mHL2xx8JkV+mmwCA3E/K5YuOaAKNMpBybISn24vPwQIq5E2HrKvBROkNgsu1K9HoQr0yuhpfDnoHjN7xTM+ItLpPWLVet6Ow0DZuiZ4Tc0iO3Tsbnzi2jbAoylEgPVfBxSLTsFtbsjKG7JMnw0Pra02RhPxcIl7vDB8G71Bz979SAFRspNBDVMk4JSihRrYbWhs9DfR1Y=
  - secure: ZggcM5qgJgZ2ehBTqlu1hOZqQ/xRzR9XfYlkd0DAUgkNXmUo3CX/7y4HnHlQpQRKls7ZI4nlNug/WkXRS8sknTmAiFxBzDjNvpOdcJM07O8dOuq4xM4c0nrCjDfFv4KImtc8bTBn8rsA28CPupHCM1pMh5DrndpTMXkKEEkM9esymQhezD9Es4DPzVyD6iStO/YytMJghKvEyjpRVQ2z+3XS+IbFnwguWhtyXL01E7pa9ii1g8pC7EhdpnpV0/jki9yzHXSK53l/Yf+5fLSEZCoRw40qnmoCc9gXe9t2a7xK2/48eAq3NsjvLm0Scj1r0iWUqdWdC9HfHditnEvBcWT0WHN2JHAudET9nidtz5x1+3Yf3bFouc79o1yOGFf5LFG47DVoMO+9GsqKyGLwcYIe2Pt9PaOSwsbhYdZaKawkYA1QrAtlRphqUDUh14rM86DdcxmjECv04hGNHTVJUNv6BgKvwatz3v8YFyT4H981XybTM1mj9pHRfw5Dp1CPN6NXp7wVy/p4WlSJtONKqUu9O+Qt7IWle0DD4cAfif9LVzXSVF+SxPj++uUXofknaOeX309nHCeDoxHX0kvp6ItstckWFGO+9TP/m3oRikfYAJjJ0ezGvbm6slY4hl94oGbQOBWJyvW/BD9C7xR9jk8KKnXBT5bK3fvWy5uSjdM=
  - secure: nfiVnhr5OsWYMlwZguDzesqXPZ57HfbljHwwdbccxF1p7hyhAkRffMbCQwWXw6A7ZC7EwDIm148s6Y+rtuqaT+KBtzzElFJ04rtqh64VQvl8fO3MNIA2wadgJinmhYISJ+sMiXgs9eycQuCvbo4zdTI++pjA6w8i5KERymYy+hnbUDRH6cXSUoiBfGc4s85J+tJXQfadHr75UoEaejgdhYhPlmJDqSo+QYSFAYGdCIEx20TsLfS/GXZebumqaGVTk5twLdd0xecvhL93AIk90Uan+PaHFJZU2zCnHe1SUUUkjHxhzyzfakOk/27II8NId0XmmVjFvU7RV876vrAUcNaqRzPjdlLjM28FVqp+QQq9Z9MUNw4oG9Q9YFzsFgbIKJB1rQtBqOf3VQ2OEEKjJapY4uJ/PgbbxR6JQUL8hAXMaIN7oiJ1O4sOUcas2k5T7N91RLXvK9Oh9UwPqngm+0DuqxromMxuJkI/6bIyLP2wOslagd0aqSA6dS9Bffx1+7OUjB8p7wckYhSwgHnCvEG1SkWc0nFZ2qFCwzr2EAT78//XfS6+PrE0U4EmPMBTp9JKwg0meTspHQUgXj4rmX7Iq1rmhz9ju37xlqOo9dPjQP5CEn1Je1Gwr1XW3fCpI+mLcbhwHHMDlo/LOOE3shFUYW0Eg++vnj9Qlmo2qMs=
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U
cache:
  directories:
  - "$HOME/.m2"
branches:
  only:
  - master
jobs:
  include:
  - stage: test
    jdk: openjdk8
    script:
    - mvn test -B -P coverage
    after_success:
    - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
    - bash <(curl -s https://codecov.io/bash)
  - stage: test
    jdk: openjdk11
    script:
    - mvn test -B
  - stage: test
    jdk: openjdk14
    script:
    - mvn test -B
before_deploy:
- openssl aes-256-cbc -K $encrypted_8154dbd2c1ae_key -iv $encrypted_8154dbd2c1ae_iv
  -in travis.key.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip_cleanup: true
  script: mv ${TRAVIS_BUILD_DIR}/dsd-service/target/dsd*.war ${TRAVIS_BUILD_DIR}/dsd-service/target/dsd.war && scp -P 3535 ${TRAVIS_BUILD_DIR}/dsd-service/target/dsd.war ${DEPLOY_USER}@${DEPLOY_HOST}:${DEPLOY_DIRECTORY}
  on:
    branch: master